Repository cicirello/user-statistician, pull requests merged in 2022-09, with the labels that each got.

#137 Added a pumpkin icon as option for top corners
  CHANGELOG.md
  src/Colors.py
  tests/tests.py
Labels: enhancement

#140 Added theme halloween, a dark theme intended for use around Halloween
  CHANGELOG.md
  src/Colors.py
  tests/tests.py
Labels: enhancement

#141 Added halloween-light - A light theme for use around Halloween
  CHANGELOG.md
  src/Colors.py
  tests/tests.py
Labels: enhancement

#142 Added batty - A light theme for use around Halloween
  CHANGELOG.md
  src/Colors.py
  tests/tests.py
Labels: enhancement

#139 Update documentation for release 1.16.0
  CHANGELOG.md
  Dockerfile
  README.md
Labels: documentation

#143 Added workflow for manually generating samples
  .github/workflows/manual-theme-sample.yml
Labels: github_actions

#163 Prepare repository for Hacktoberfest contributions
  README.md
Labels: documentation

#164 Add Romanian translation
  src/StatConfig.py
Labels: hacktoberfest-accepted
