Repository cicirello/user-statistician, pull requests merged in 2022-10, with the labels that each got.

#166 Add Dutch Translations
  src/StatConfig.py
Labels: enhancement, hacktoberfest-accepted

#165 Add Thai language
  src/StatConfig.py
Labels: enhancement, hacktoberfest-accepted

#167 🇳🇴 Added Norwegian translation
  src/StatConfig.py
Labels: enhancement, hacktoberfest-accepted

#170 Update docs and preparation for release 1.17.0
  CHANGELOG.md
  README.md
Labels: documentation

#172 feat: add Hungarian localization #161
  src/StatConfig.py
Labels: enhancement, hacktoberfest-accepted

#173 Prepare for release 1.18.0 with documentation updates
  CHANGELOG.md
  README.md
Labels: documentation

#175 Added workflow to manage stale pull-requests
  .github/workflows/stale.yml
Labels: github_actions

#178 Add Santali language
  src/StatConfig.py
Labels: enhancement, hacktoberfest-accepted

#182 feat: add Serbian localization #181
  src/StatConfig.py
Labels: enhancement, hacktoberfest-accepted

#184 Replaced use of GitHub Action's deprecated set-output
  CHANGELOG.md
  src/Statistician.py
  src/UserStatistician.py
Labels: bug

#185 Prepare release 1.19.0
  CHANGELOG.md
  README.md
Labels: documentation

#186 Added Odia language
  src/StatConfig.py
Labels: enhancement, hacktoberfest-accepted

#190 Backwards compatibility for self-hosted runners without support for new `GITHUB_OUTPUT` env file
  CHANGELOG.md
  src/Statistician.py
Labels: bug

#191 Bump Python to 3.11 in CI/CD workflows and in Docker container
  .github/workflows/build.yml
  CHANGELOG.md
  Dockerfile
Labels: dependencies, github_actions, docker

#192 Prepare release 1.20.0
  CHANGELOG.md
  README.md
Labels: documentation
