Repository cicirello/user-statistician, pull requests merged in 2023-10, with the labels that each got.

#230 feat: Added Swedish language translation
  src/StatConfig.py
  src/locales/sv.json
Labels: enhancement, hacktoberfest-accepted

#234 Bumped actions/checkout to v4 in quickstart / sample workflows
  CHANGELOG.md
  README.md
  quickstart/all-defaults.yml
  quickstart/contributions.yml
  quickstart/dark-dimmed.yml
  quickstart/dark.yml
  quickstart/languages.yml
  quickstart/multiple-stats-cards.yml
  quickstart/repositories.yml
Labels: documentation, dependencies

#235 feat : Added Malayalam translation #231
  src/StatConfig.py
  src/locales/ml.json
Labels: enhancement, hacktoberfest-accepted

#236 Feat: Add Finnish translation
  src/StatConfig.py
  src/locales/fi.json
Labels: enhancement, hacktoberfest-accepted

#237 update docs for release 1.21.0
  CHANGELOG.md
  README.md
Labels: documentation

#241 Update docs with new locale and prepare release 1.22.0
  CHANGELOG.md
  README.md
Labels: documentation
