Repository cicirello/user-statistician, pull requests merged in 2023-09, with the labels that each got.

#219 Prepare release 1.20.3
  CHANGELOG.md
Labels: documentation

#221 Refactored to extract locales from Python dictionaries to JSON files
  .gitattributes
  CHANGELOG.md
  README.md
  src/ColorUtil.py
  src/PieChart.py
  src/StatConfig.py
  src/Statistician.py
  src/StatsImageGenerator.py
  src/TextLength.py
  src/UserStatistician.py
  src/locales/bn.json
  src/locales/de.json
  src/locales/en.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/hi.json
  src/locales/hu.json
  src/locales/id.json
  src/locales/it.json
  src/locales/ja.json
  src/locales/ko.json
  src/locales/lt.json
  src/locales/nl.json
  src/locales/no.json
  src/locales/or.json
  src/locales/pl.json
  src/locales/pt.json
  src/locales/ro.json
  src/locales/ru.json
  src/locales/sat.json
  src/locales/sr.json
  src/locales/th.json
  src/locales/tr.json
  src/locales/uk.json
  tests/tests.py
  util/refactor-locales-to-json.py
Labels: refactor

#222 Prepare release 1.20.4
  .github/workflows/generate-samples.yml
  CHANGELOG.md
Labels: documentation

#224 Resolved issue with failing to commit and push, a bug introduced in v1.20.3.
  CHANGELOG.md
  src/UserStatistician.py
Labels: bug

#227 Updated Tagalog (tl) translations
  src/StatConfig.py
  src/locales/tl.json
Labels: enhancement, hacktoberfest-accepted

#229 Update list of blog posts from DEV about the action in README
  README.md
Labels: documentation
